import { buildSchedule } from './scheduler.js';
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const defaultAvailability = {0:{enabled:false,start:'09:00',end:'17:00'},1:{enabled:true,start:'16:00',end:'20:00'},2:{enabled:true,start:'17:00',end:'21:00'},3:{enabled:false,start:'16:00',end:'20:00'},4:{enabled:true,start:'16:00',end:'19:00'},5:{enabled:true,start:'16:00',end:'22:00'},6:{enabled:true,start:'09:00',end:'17:00'}};
let state = load(), viewDate = new Date();
const newId = () => `assignment-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;

function load() { try { const saved = {...{assignments:[],availability:defaultAvailability,theme:'light',schedule:[]},...JSON.parse(localStorage.getItem('assignment-planner') || '{}')}; saved.assignments = saved.assignments.map(task => ({...task, priority:(task.priority || 'medium').toLowerCase(), completedMinutes:task.completedMinutes || 0})); return saved; } catch { return {assignments:[],availability:defaultAvailability,theme:'light',schedule:[]}; } }
function persist() { localStorage.setItem('assignment-planner', JSON.stringify(state)); }
function reschedule() { const result = buildSchedule(state.assignments, state.availability); state.schedule = result.sessions; state.overloaded = result.overloaded; persist(); render(); }
const time = value => new Date(value).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});
const date = value => new Date(value).toLocaleDateString([], {month:'short',day:'numeric'});
const duration = minutes => minutes % 60 ? `${Math.floor(minutes/60)}h ${minutes%60}m` : `${Math.floor(minutes/60)}h`;

function render() { document.body.classList.toggle('dark',state.theme === 'dark'); $('#themeToggle span').textContent = state.theme === 'dark' ? 'Light mode' : 'Dark mode'; renderCalendar('#calendar'); renderCalendar('#calendarAlt'); renderUpcoming(); renderStats(); renderAvailability(); }
function renderCalendar(target) { const element=$(target); if (!element) return; const year=viewDate.getFullYear(), month=viewDate.getMonth(), first=new Date(year,month,1), start=new Date(year,month,1-first.getDay()), today=new Date(); $('#monthTitle').textContent=viewDate.toLocaleDateString([],{month:'long',year:'numeric'}); element.innerHTML=''; for(let index=0;index<42;index++){const day=new Date(start);day.setDate(start.getDate()+index);const sessions=state.schedule.filter(session=>new Date(session.end)>Date.now() && new Date(session.start).toDateString()===day.toDateString());const deadlines=state.assignments.filter(task=>!task.completed && new Date(task.deadline).toDateString()===day.toDateString());const cell=document.createElement('div');cell.className=`day ${day.getMonth()===month?'':'muted'} ${day.toDateString()===today.toDateString()?'today':''}`;cell.innerHTML=`<div class="day-number">${day.getDate()}</div>${deadlines.map(task=>`<div class="deadline" data-id="${task.id}">Due ${time(task.deadline)} · ${task.title}</div>`).join('')}${sessions.slice(0,Math.max(0,3-deadlines.length)).map(session=>`<div class="session ${session.priority}" data-id="${session.assignmentId}">${time(session.start)} ${session.title}</div>`).join('')}${sessions.length>3?`<div class="session">+${sessions.length-3} more</div>`:''}`;cell.onclick=event=>event.target.dataset.id?openDetail(event.target.dataset.id):day.getMonth()===month&&openDay(day);element.appendChild(cell);}}
function renderStats() { const active=state.assignments.filter(task=>!task.completed); $('#activeCount').textContent=active.length; $('#hoursScheduled').textContent=duration(state.schedule.reduce((sum,session)=>sum+session.minutes,0)); const next=[...active].sort((a,b)=>new Date(a.deadline)-new Date(b.deadline))[0]; $('#nextDeadline').textContent=next?date(next.deadline):'—'; $('#nextDeadlineText').textContent=next?next.title:'Add an assignment'; $('#warning').classList.toggle('hidden',!state.overloaded); $('#sessionCount').textContent=state.schedule.filter(session=>new Date(session.end)>Date.now()).length; }
function renderUpcoming() { const element=$('#upcomingList'), sessions=state.schedule.filter(session=>new Date(session.end)>Date.now()).sort((a,b)=>new Date(a.start)-new Date(b.start)).slice(0,12); element.innerHTML=sessions.length?sessions.map(session=>`<article class="upcoming-item" data-id="${session.assignmentId}" data-session="${session.id}"><input type="checkbox" aria-label="Mark this work session complete"><div><div class="task-title">${session.title}</div><div class="task-meta">${date(session.start)} · ${time(session.start)}–${time(session.end)}</div><span class="badge ${session.priority}">${session.priority.toUpperCase()} PRIORITY · ${duration(session.minutes)}</span></div></article>`).join(''):'<div class="empty">Your schedule is clear.<br>Add an assignment to get started.</div>'; $$('.upcoming-item').forEach(item=>item.onclick=event=>event.target.matches('input')?completeSession(item.dataset.session):openDetail(item.dataset.id)); }
function renderAvailability() { const element=$('#availability'); if(!element)return; element.innerHTML=days.map((day,index)=>{const setting=state.availability[index];return `<div class="availability-row"><label><input type="checkbox" data-day="${index}" class="available" ${setting.enabled?'checked':''}> ${day}</label><input type="time" data-start="${index}" value="${setting.start}" ${setting.enabled?'':'disabled'}><input type="time" data-end="${index}" value="${setting.end}" ${setting.enabled?'':'disabled'}></div>`}).join(''); $$('.available').forEach(box=>box.onchange=()=>box.closest('.availability-row').querySelectorAll('input[type=time]').forEach(input=>input.disabled=!box.checked)); }
function modal(content) { $('#modalRoot').innerHTML=`<div class="modal-backdrop"><section class="modal">${content}</section></div>`; $('.modal-backdrop').onclick=event=>{if(event.target===event.currentTarget)closeModal();}; $$('[data-close]').forEach(button=>button.onclick=closeModal); }
function closeModal() { $('#modalRoot').innerHTML=''; }
function localDateTime(value) { const d = new Date(value); const offset = d.getTimezoneOffset() * 60_000; return new Date(d - offset).toISOString().slice(0,16); }
function defaultDeadline() { const d = new Date(); d.setDate(d.getDate() + 3); d.setHours(23, 59, 0, 0); return localDateTime(d); }
function openAdd(task={}) { modal(`<div class="modal-head"><div><p class="eyebrow">${task.id?'UPDATE':'NEW'} ASSIGNMENT</p><h2>${task.id?'Edit assignment':'What needs doing?'}</h2></div><button class="close" data-close>×</button></div><form id="taskForm"><div class="form-grid"><label class="field full">ASSIGNMENT NAME<input required name="title" value="${task.title||''}" placeholder="e.g. Biology lab report"></label><label class="field">COURSE<input required name="course" value="${task.course||''}" placeholder="e.g. Biology"></label><label class="field">DEADLINE<input required type="datetime-local" name="deadline" value="${task.deadline?localDateTime(task.deadline):defaultDeadline()}"></label><label class="field">HOURS<input required type="number" min="0" name="hours" value="${task.duration?Math.floor(task.duration/60):1}"></label><label class="field">MINUTES<input required type="number" min="0" max="59" name="mins" value="${task.duration?task.duration%60:0}"></label><label class="field">PRIORITY<select name="priority">${['high','medium','low'].map(priority=>`<option ${task.priority===priority?'selected':''}>${priority.toUpperCase()}</option>`).join('')}</select></label><label class="field full">NOTES<textarea name="notes" rows="3" placeholder="Anything helpful to remember…">${task.notes||''}</textarea></label></div><div class="modal-actions"><button type="button" class="secondary" data-close>Cancel</button><button type="submit" class="primary">Save & plan</button></div></form>`); $('#taskForm').onsubmit=event=>{event.preventDefault();const form=new FormData(event.target), total=(+form.get('hours')*60)+(+form.get('mins'));if(total<30)return alert('Please enter at least 30 minutes.');const deadlineValue=form.get('deadline');if(!deadlineValue)return alert('Choose a deadline before saving.');const assignment={id:task.id||newId(),title:form.get('title'),course:form.get('course'),deadline:new Date(deadlineValue).toISOString(),duration:total,priority:form.get('priority').toLowerCase(),notes:form.get('notes'),completed:task.completed||false,completedMinutes:task.completedMinutes||0};state.assignments=task.id?state.assignments.map(item=>item.id===task.id?assignment:item):[...state.assignments,assignment];closeModal();reschedule();}; }
function openDetail(id) { const task=state.assignments.find(item=>item.id===id); if(!task)return; const sessions=state.schedule.filter(session=>session.assignmentId===id); modal(`<div class="modal-head"><div><p class="eyebrow">${task.course}</p><h2>${task.title}</h2></div><button class="close" data-close>×</button></div><div class="detail-list"><div><span>Deadline</span><b>${new Date(task.deadline).toLocaleString()}</b></div><div><span>Priority</span><b class="badge ${task.priority}">${task.priority}</b></div><div><span>Progress</span><b>${duration(task.completedMinutes||0)} of ${duration(task.duration)}</b></div><div><span>Remaining sessions</span><b>${sessions.length} planned</b></div></div>${task.notes?`<p class="muted">${task.notes}</p>`:''}<div class="modal-actions"><button class="secondary" id="deleteTask">Delete</button><button class="secondary" id="editTask">Edit</button><button class="primary" id="completeTask">Mark complete</button></div>`); $('#editTask').onclick=()=>openAdd(task); $('#deleteTask').onclick=()=>{if(confirm('Delete this assignment?')){state.assignments=state.assignments.filter(item=>item.id!==id);closeModal();reschedule();}}; $('#completeTask').onclick=()=>{markAssignmentComplete(id);closeModal();}; }
function completeSession(id) { const session=state.schedule.find(item=>item.id===id); if(!session)return; state.assignments=state.assignments.map(task=>{if(task.id!==session.assignmentId)return task;const completedMinutes=Math.min(task.duration,(task.completedMinutes||0)+session.minutes);return {...task,completedMinutes,completed:completedMinutes>=task.duration};}); reschedule(); }
function markAssignmentComplete(id) { state.assignments=state.assignments.map(task=>task.id===id?{...task,completed:true,completedMinutes:task.duration}:task); reschedule(); }
function openDay(day) { const sessions=state.schedule.filter(session=>new Date(session.end)>Date.now()&&new Date(session.start).toDateString()===day.toDateString()); modal(`<div class="modal-head"><div><p class="eyebrow">${day.toLocaleDateString([],{weekday:'long'})}</p><h2>${day.toLocaleDateString([],{month:'long',day:'numeric'})}</h2></div><button class="close" data-close>×</button></div>${sessions.length?'<div class="detail-list">'+sessions.map(session=>`<div><span>${time(session.start)}–${time(session.end)}</span><b>${session.title}</b></div>`).join('')+'</div>':'<p class="muted">No work is planned for this day.</p>'}`); }
$('#addTask').onclick=()=>openAdd(); $('#prevMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);render();}; $('#nextMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);render();}; $('#todayButton').onclick=()=>{viewDate=new Date();render();}; $('#themeToggle').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';persist();render();}; $('#saveAvailability').onclick=()=>{days.forEach((_,index)=>state.availability[index]={enabled:$(`.available[data-day="${index}"]`).checked,start:$(`[data-start="${index}"]`).value,end:$(`[data-end="${index}"]`).value});reschedule();}; $$('.nav-item').forEach(button=>button.onclick=()=>{$$('.nav-item').forEach(item=>item.classList.remove('active'));button.classList.add('active');$$('.page').forEach(page=>page.classList.remove('active'));$(`#${button.dataset.page}Page`).classList.add('active');$('#pageTitle').innerHTML=button.dataset.page==='settings'?'Design a routine that <em>works.</em>':button.dataset.page==='calendar'?'Everything, <em>in its place.</em>':'Make room for <em>what matters.</em>';});
reschedule();
setInterval(reschedule, 60_000);