require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');
const app = express();
const port = process.env.PORT || 3000;
app.use(cors());
app.use(express.json());
app.get('/api/health', (_req, res) => res.json({ status: 'ok', app: 'Assignment Planner' }));
app.use(express.static(path.join(__dirname, '../client')));
app.get('*', (_req, res) => res.sendFile(path.join(__dirname, '../client/index.html')));
app.listen(port, () => console.log(`Assignment Planner running at http://localhost:${port}`));
